#include "main.h"

artifacti bsmeta<artifacti>::elements[] = {{},
{12, Knowledge, 4, "Ultimate Book of Knowledge", "%1 увеличивает ваши знания на %2i."},
{12, Attack, 4, "Ultimate Sword of Dominion", "%1 увеличивает вашу атаку %2i."},
{12, Defence, 4, "Ultimate Cloak of Protection", "%1 увеличивает вашу защиту на %2i."},
{12, SpellPower, 4, "Ultimate Wand of Magic", "The %1 increases your spell power by %2i."},
{6, AttackDefence, 4, "Ultimate Shield", "The %1 increases your attack and defense skills by %2i each."},
{6, SpellPowerKnowledge, 4, "Ultimate Staff", "The %1 increases your spell power and knowledge by %2i each."},
{4, AllAbilities, 4, "Ultimate Crown", "The %1 increases each of your basic skills by %2i points."},
{5000, Gold, 4, "Golden Goose", "The %1 brings in an income of %2i gold per turn."},
{4, SpellPower, 3, "Arcane Necklace of Magic", "The %1 increases your spell power by %2i."},
{2, SpellPower, 2, "Caster's Bracelet of Magic", "The %1 increases your spell power by %2i."},
{2, SpellPower, 2, "Mage's Ring of Power", "The %1 increases your spell power by %2i."},
{3, SpellPower, 3, "Witch's Broach of Magic", "The %1 increases your spell power by %2i."},
{1, MoraleStat, 1, "Medal of Valor", "The %1 increases your morale."},
{1, MoraleStat, 1, "Medal of Courage", "The %1 increases your morale."},
{1, MoraleStat, 1, "Medal of Honor", "The %1 increases your morale."},
{1, MoraleStat, 1, "Medal of Distinction", "The %1 increases your morale."},
{-2, MoraleStat, -1, "Fizbin of Misfortune", "The %1 greatly decreases your morale by %2i."},
{1, Attack, 1, "Thunder Mace of Dominion", "%1 увеличивает вашу атаку на %2i."},
{1, Defence, 1, "Armored Gauntlets of Protection", "The %1 increase your defense skill by %2i."},
{1, Defence, 1, "Defender Helm of Protection", "The %1 increases your defense skill by %2i."},
{1, Attack, 1, "Giant Flail of Dominion", "The %1 increases your attack skill by %2i."},
{2, {}, 3, "Ballista of Quickness", "The %1 lets your catapult fire twice per combat round."},
{2, Defence, 2, "Stealth Shield of Protection", "The %1 increases your defense skill by %2i."},
{3, Attack, 3, "Dragon Sword of Dominion", "The %1 increases your attack skill by %2i."},
{2, Attack, 2, "Power Axe of Dominion", "The %1 increases your attack skill by %2i."},
{3, Defence, 3, "Divine Breastplate of Protection", "The %1 increases your defense skill by %2i."},
{2, Knowledge, 2, "Minor Scroll of Knowledge", "The %1 increases your knowledge by %2i."},
{3, Knowledge, 3, "Major Scroll of Knowledge", "The %1 increases your knowledge by %2i."},
{4, Knowledge, 3, "Superior Scroll of Knowledge", "The %1 increases your knowledge by %2i."},
{5, Knowledge, 3, "Foremost Scroll of Knowledge", "The %1 increases your knowledge by %2i."},
{1000, Gold, 3, "Endless Sack of Gold", "The %1 provides you with %2i gold per day."},
{500, Gold, 3, "Endless Bag of Gold", "The %1 provides you with %2i gold per day."},
{100, Gold, 2, "Endless Purse of Gold", "The %1 provides you with %2i gold per day."},
{0, {}, 3, "Nomad Boots of Mobility", "The %1 increase your movement on land."},
{0, {}, 3, "Traveler's Boots of Mobility", "The %1 increase your movement on land."},
{1, Luck, 1, "Lucky Rabbit's Foot", "The %1 increases your luck in combat."},
{1, Luck, 1, "Golden Horseshoe", "The %1 increases your luck in combat."},
{1, Luck, 1, "Gambler's Lucky Coin", "The %1 increases your luck in combat."},
{1, Luck, 1, "Four-Leaf Clover", "The %1 increases your luck in combat."},
{0, {}, 3, "True Compass of Mobility", "The %1 increases your movement on land and sea."},
{0, {}, 2, "Sailor's Astrolabe of Mobility", "The %1 increases your movement on sea."},
{0, {}, 2, "Evil Eye", "The %1 reduces the casting cost of curse spells by half."},
{2, {}, 1, "Enchanted Hourglass", "The %1 extends the duration of all your spells by %2i turns."},
{0, {}, 2, "Gold Watch", "The %1 doubles the effectiveness of your hypnotize spells."},
{0, {}, 2, "Skullcap", "The %1 halves the casting cost of all mind influencing spells."},
{0, {}, 1, "Ice Cloak", "The %1 halves all damage your troops take from cold spells."},
{0, {}, 1, "Fire Cloak", "The %1 halves all damage your troops take from fire spells."},
{0, {}, 1, "Lightning Helm", "The %1 halves all damage your troops take from lightning spells."},
{50, Cold, 2, "Evercold Icicle", "The %1 causes your cold spells to do %2i percent more damage to enemy troops."},
{50, Fire, 2, "Everhot Lava Rock", "The %1 causes your fire spells to do %2i percent more damage to enemy troops."},
{50, Lighting, 3, "Lightning Rod", "The %1 causes your lightning spells to do %2i percent more damage to enemy troops."},
{0, {}, 1, "Кольцо змеи", "The %1 halves the casting cost of all your bless spells."},
{0, {}, 2, "Анкх", "The %1 doubles the effectiveness of all your resurrect and animate spells."},
{0, Summon, 2, "Книга элементов", "The %1 doubles the effectiveness of all your summoning spells."},
{0, {}, 2, "Кольцо элементов", "The %1 halves the casting cost of all summoning spells."},
{0, {}, 1, "Святой кулон", "The %1 makes all your troops immune to curse spells."},
{0, {}, 1, "Амулет свободной воли", "The %1 makes all your troops immune to hypnotize spells."},
{0, {}, 1, "Кулон движения", "The %1 makes all your troops immune to death spells."},
{0, {}, 1, "Амулет спокойствия", "The %1 makes all your troops immune to berserk spells."},
{0, {}, 1, "Seeing-eye Pendant", "The %1 makes all your troops immune to blindness spells."},
{0, {}, 1, "Кулон движения", "The %1 makes all your troops immune to paralyze spells."},
{0, {}, 1, "Pendant of Death", "The %1 makes all your troops immune to holy spells."},
{0, {}, 3, "Wand of Negation", "The %1 protects your troops from the Dispel Magic spell."},
{50, {}, 1, "Golden Bow", "The %1 eliminates the %2i percent penalty for your troops shooting past obstacles. (e.g. castle walls)"},
{1, {}, 1, "Telescope", "The %1 increases the amount of terrain your hero reveals when adventuring by %2i extra square."},
{10, {}, 1, "Statesman's Quill", "The %1 reduces the cost of surrender to %2i percent of the total cost of troops you have in your army."},
{10, {}, 3, "Wizard's Hat", "The %1 increases the duration of your spells by %2i turns."},
{2, Mysticism, 2, "Кольцо Могущества", "The %1 returns %2i extra power points/turn to your hero."},
{0, {}, 2, "Ammo Cart", "The %1 provides endless ammunition for all your troops that shoot."},
{-250, Gold, -1, "Подать", "The %1 costs you %2i gold pieces/turn."},
{0, {}, -1, "Ужасная маска", "The %1 prevents all 'wandering' armies from joining your hero."},
{1, Sulfur, 3, "Бесконечный мешочек Серы", "The %1 provides %2i unit of sulfur per day."},
{1, Mercury, 3, "Бесконечный сосуд Ртути", "The %1 provides %2i unit of mercury per day."},
{1, Gems, 3, "Бесконечный мешочек Драгоценностей", "The %1 provides %2i unit of gems per day."},
{1, Wood, 2, "Бесконечная вязанка Дерева", "The %1 provides %2i unit of wood per day."},
{1, Ore, 2, "Бесконечная тачка Камней", "The %1 provides %2i unit of ore per day."},
{1, Crystal, 3, "Бесконечный мешочек Кристаллов", "The %1 provides %2i unit of crystal/day."},
{1, AttackDefence, 2, "Шипастый шлем", "The %1 increases your attack and defense skills by %2i each."},
{2, AttackDefence, 3, "Шипастый щит", "The %1 increases your attack and defense skills by %2i each."},
{1, SpellPowerKnowledge, 2, "Белая жемчужина", "The %1 increases your spell power and knowledge by %2i each."},
{2, SpellPowerKnowledge, 3, "Черная жемчужина", "The %1 increases your spell power and knowledge by %2i each."},
//
{0, {}, 0, "Волшебная книга", "The %1 enables you to cast spells."},
};
assert_enum(artifact, MagicBook);